name: flare_flutter
description: Vector design and runtime animation for Flutter.
version: 1.5.7
author: "2Dimensions Team <info@2dimensions.com>"
homepage: https://github.com/2d-inc/Flare-Flutter
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.7.8+hotfix.3"
dependencies:
  flutter_web: any
  flare_dart: ^1.4.5

dev_dependencies:
  flutter_web_test: any

  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0

  test: ^1.3.4

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test

